START TRANSACTION;

ALTER TABLE "Files" DROP COLUMN "Name";

ALTER TABLE "Files" ADD "DeletedAt" timestamp with time zone NULL;

ALTER TABLE "Files" ADD "DeletedBy" text NULL;

ALTER TABLE "Files" ADD "IsDeleted" boolean NOT NULL DEFAULT FALSE;

CREATE TABLE "Categories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone NULL,
    "DeletedBy" text NULL,
    CONSTRAINT "PK_Categories" PRIMARY KEY ("Id")
);

CREATE TABLE "Books" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "PreviewImageUrl" text NOT NULL,
    "CategoryId" integer NOT NULL,
    "UserSocialId" integer NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone NULL,
    "DeletedBy" text NULL,
    CONSTRAINT "PK_Books" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Books_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Books_UsersSocial_UserSocialId" FOREIGN KEY ("UserSocialId") REFERENCES "UsersSocial" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Books_CategoryId" ON "Books" ("CategoryId");

CREATE INDEX "IX_Books_UserSocialId" ON "Books" ("UserSocialId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230106130345_AddedBookCategory', '6.0.10');

COMMIT;

