CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "UsersAdmin" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Username" text NOT NULL,
    "Password" text NOT NULL,
    "LoginsCount" integer NULL,
    "LastLogin" timestamp with time zone NULL,
    CONSTRAINT "PK_UsersAdmin" PRIMARY KEY ("Id")
);

CREATE TABLE "UsersSocial" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Username" text NOT NULL,
    "FirstName" text NULL,
    "LastName" text NULL,
    "Email" text NOT NULL,
    "UserPicture" text NOT NULL,
    "ProviderUserId" text NOT NULL,
    "OAuthProvider" integer NOT NULL,
    CONSTRAINT "PK_UsersSocial" PRIMARY KEY ("Id")
);

CREATE TABLE "Files" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "FileName" text NOT NULL,
    "FileType" text NOT NULL,
    "FileSize" numeric NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UserSocialId" integer NOT NULL,
    CONSTRAINT "PK_Files" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Files_UsersSocial_UserSocialId" FOREIGN KEY ("UserSocialId") REFERENCES "UsersSocial" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Payments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Amount" numeric NOT NULL,
    "Currency" text NOT NULL,
    "OrderId" text NOT NULL,
    "Status" integer NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "UserSocialId" integer NOT NULL,
    CONSTRAINT "PK_Payments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Payments_UsersSocial_UserSocialId" FOREIGN KEY ("UserSocialId") REFERENCES "UsersSocial" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Files_UserSocialId" ON "Files" ("UserSocialId");

CREATE INDEX "IX_Payments_UserSocialId" ON "Payments" ("UserSocialId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20221019102212_Initial', '6.0.10');

COMMIT;

